CREATE TABLE NOTE (
                      ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
                      STUDY_ID    BIGINT NOT NULL,
                      USER_ID     BIGINT NOT NULL,
                      TITLE       VARCHAR(255) NOT NULL,
                      CONTENT     TEXT,
                      CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      UPDATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT NOTE_USER_FK FOREIGN KEY (USER_ID) REFERENCES HC_USER(ID)
);

CREATE INDEX IDX_NOTE_STUDY_ID ON NOTE(STUDY_ID);
CREATE INDEX IDX_NOTE_USER_ID ON NOTE(USER_ID);
